### ISSUE TITLE
EMMA() - Error in eigen(A) : infinite or missing values in 'x'

### ISSUE THREAD

**Issue by RLumSK** [coffeemuggler/EMMAgeo#2]
## Decription

If the input matrix for the function `EMMA()` contains 0 values for a grain size class (something that may just be returned by the grain size analyser), the function returns the following error message: 

``` 
Error in eigen(A) : infinite or missing values in 'x'
```

This should not happen, and it is misleading since neither value is `Inf` nor `missing`. 
Supplement: This bug also breaks the shiny app with an even less detailed error message. 

## Example

```r
data(example_X)
X[,1] <- 0  

## perform EMMA with 5 end-members
EM <- EMMA(X = X, q = 5, l = 0.05, c = 100, plot = TRUE)
```

**Comment by coffeemuggler** [comment]
Indeed, zero-only columns cannot be modelled with EMMA. Now explicitly included as a test in the function.

**Comment by RLumSK** [comment]
Perhaps such a test could be implemented with a useful comment in `check.data()`? I guess this would help the inexperienced user.
