### ISSUE TITLE
EMMA() - character vector for argument ID leads to a crash

### ISSUE THREAD

**Issue by RLumSK** [coffeemuggler/EMMAgeo#5]
## Observation 

The manual states: 

>  ID | Numeric or character vector, optional sample IDs of the same length as rows of X.

However, providing a character vector leads to 

```
Error in ID * barplot_names_match : 
  non-numeric argument to binary operator
In addition: Warning message:
In pretty.default(ID, n = round(length(ID)/5)) : NAs introduced by coercion
```

## Running example

```r
## load example data and set phi-vector
data(example_X)
phi <- seq(from = 1, to = 10, length.out = ncol(X))

## perform EMMA with 5 end-members
EM <- EMMA(X = X, ID = paste0("a", 1:100), q = 5, l = 0.05, c = 100, plot = TRUE)
```

## Further remarks

The x-axis labels in the lower right plot are not complete. For example, for a dataset with only five rows, only a "5" is labelled.

**Comment by coffeemuggler** [comment]
Thanks, bug fixed, though a bit different, which was necessary to align with general layout of the function and work flow.
